### ISSUE TITLE
服务器挂了

### ISSUE THREAD

**Issue by QianHong** [WhiteVermouth/intellij-investor-dashboard#15]

**Comment by WhiteVermouth** [comment]
新浪把API关了，正在找替代方案

**Comment by WhiteVermouth** [comment]
新版 **v1.7.0** 已修复，由于新浪关闭API导致的不可用已使用腾讯API替代解决。目前正在等待JetBrains审核，可以在审核通过后升级，或者也可以直接在[Release](https://github.com/WhiteVermouth/intellij-investor-dashboard/releases/tag/v1.7.0)下载zip包，然后在IDE内**Install Plugin from Disk**。
