### ISSUE TITLE
插件不能用了

### ISSUE THREAD

**Issue by uxawseny** [WhiteVermouth/intellij-investor-dashboard#16]
插件不能用了，貌似是服务挂了

**Comment by WhiteVermouth** [comment]
新版 **v1.7.0** 已修复，由于新浪关闭API导致的不可用已使用腾讯API替代解决。目前正在等待JetBrains审核，可以在审核通过后升级，或者也可以直接在[Release](https://github.com/WhiteVermouth/intellij-investor-dashboard/releases/tag/v1.7.0)下载zip包，然后在IDE内**Install Plugin from Disk**。
