### ISSUE TITLE
希望能添加一个拖拽移动功能

### ISSUE THREAD

**Issue by JokingLove** [WhiteVermouth/intellij-investor-dashboard#22]
首先，感谢大佬
能否添加一个拖拽某个股票，可以移动到想要的位置

**Comment by WhiteVermouth** [comment]
股票顺序的调整可以通过点击工具栏上面的“三条横”，打开对话框调整，支持拖拽。
<img width="412" alt="image" src="https://user-images.githubusercontent.com/13076049/183943631-088a4c47-a425-4a37-97d9-2a506d945abd.png">

**Comment by JokingLove** [comment]
> 股票顺序的调整可以通过点击工具栏上面的“三条横”，打开对话框调整，支持拖拽。 <img alt="image" width="412" src="https://user-images.githubusercontent.com/13076049/183943631-088a4c47-a425-4a37-97d9-2a506d945abd.png">

thanks, 找到了，好像只能一步一步通过按钮移动。

**Comment by WhiteVermouth** [comment]
支持点击按钮上下移动，也支持在列表上直接拖拽的

**Comment by JokingLove** [comment]
> 支持点击按钮上下移动，也支持在列表上直接拖拽的

嗯，我的按钮上下移动没问题，直接拖拽好像有点问题。不过没关系，只要能移就可以了 👍
