### ISSUE TITLE
如果不能区分品种，价格都显示3位小数

### ISSUE THREAD

**Issue by zybingliu** [WhiteVermouth/intellij-investor-dashboard#24]
现在不同品种，不同市场，价格有的是2位小数，有的是3位小数；

如果不能区分品种，价格显示都3位小数吧，这样不会丢失信息

**Comment by WhiteVermouth** [comment]
v1.9.1已修复三位小数价格的显示问题

**Comment by zybingliu** [comment]
1.9.1还是只显示2位小数

![image](https://user-images.githubusercontent.com/995626/222372723-2e5cbb4f-abb4-41fb-b42b-c6818e600368.png)

**Comment by zybingliu** [comment]
准确的讲，应该是ETF品种强制显示3位小数，而不应该最后以为是0就不显示，如上图第一行， 该ETF品种收盘价格是0.750，价格显示了0.75，这样显示不太习惯

**Comment by zybingliu** [comment]
包括上图最后一个股票是港股，收盘是 362.800， 显示了362.8

**Comment by WhiteVermouth** [comment]
现在是依据实际价格显示，只有实际价格是三位小数的会显示三位小数。
