### ISSUE TITLE
大佬这个数据可以支持导出吗,导入到另一台机器的idea

### ISSUE THREAD

**Issue by ICLXL** [WhiteVermouth/intellij-investor-dashboard#3]

**Comment by WhiteVermouth** [comment]
现在可以通过复制IDE配置目录下的stocker-config.xml到目标机器的IDE对应配置目录下来完成同步。
不同平台IDE的配置目录地址可以参考如下文档：
https://www.jetbrains.com/help/idea/tuning-the-ide.html?_ga=2.11242935.206513735.1606655680-1650010321.1602492368#config-directory
比如在mac下，将~/Library/Application Support/JetBrains/IntelliJIdea2020.2/options/stocker-config.xml复制到目标机器的相同位置。
