### ISSUE TITLE
大佬, 更新之后颜色太扎眼了..

### ISSUE THREAD

**Issue by shgdym** [WhiteVermouth/intellij-investor-dashboard#4]
![image](https://user-images.githubusercontent.com/17404063/100956662-e8400700-3553-11eb-9432-2062fa82b471.png)

**Comment by WhiteVermouth** [comment]
好的，会继续改的，感谢反馈

**Comment by WhiteVermouth** [comment]
升级1.2.1看下

**Comment by shgdym** [comment]
辛苦了
