### ISSUE TITLE
添加不了etf

### ISSUE THREAD

**Issue by JasperWong** [WhiteVermouth/intellij-investor-dashboard#8]
加入搜索功能后添加不了etf了,例如sh515790,sz159825

**Comment by WhiteVermouth** [comment]
下个版本修复

**Comment by WhiteVermouth** [comment]
v1.4.3已修复该问题，目前正等待JetBrains审核。在审核通过后升级即可，或者也可以直接下载GitHub Release中的v1.4.3安装包，在IDE中Install Plugin from Disk

**Comment by JasperWong** [comment]
> v1.4.3已修复该问题，目前正等待JetBrains审核。在审核通过后升级即可，或者也可以直接下载GitHub Release中的v1.4.3安装包，在IDE中Install Plugin from Disk

点赞
