### ISSUE TITLE
选项卡stocker不显示

### ISSUE THREAD

**Issue by wzbos** [WhiteVermouth/intellij-investor-dashboard#9]
选项卡stocker不显示，view->tool windows 和 preferences->tools 下面也没有，重装as 和 stocker 都不管用 
Android studio 4.1.3

**Comment by WhiteVermouth** [comment]
v1.4.3已修复该问题，目前正等待JetBrains审核。在审核通过后升级即可，或者也可以直接下载GitHub Release中的v1.4.3安装包，在IDE中Install Plugin from Disk
